import { Link } from "react-router-dom";
import { CONTRACT_ADDRESS, EXPLORER_URL } from "../config";

export default function About() {
  const steps = [["01", "Register", "A wallet submits a public HTTPS document and a short description of what matters."], ["02", "Commit", "Validators fetch the page and agree on one baseline snapshot plus its Keccak-256 identity."], ["03", "Check", "A later request asks validators to read the current page and compare meaning, not markup."], ["04", "Record", "The verdict, severity, reasoning, citations, and current snapshot are stored as a permanent report."]];
  return <div className="container-wide page"><div className="page-heading"><div><span className="section-index">ABOUT / CONSENSUS DESIGN</span><h1>Meaning needs<br /><em>more than one reader.</em></h1><p>SourceWatch is a practical example of GenLayer's Optimistic Democracy: a leader proposes, independent validators evaluate, and the chain accepts only an equivalent result.</p></div></div><div className="about-flow">{steps.map(([number, title, body]) => <div className="about-step" key={number}><b>{number}</b><div><h2>{title}</h2><p>{body}</p></div></div>)}</div><section className="about-rule"><div><span className="section-index">EQUIVALENCE PRINCIPLE</span><h2>Agree on the signal.<br />Allow natural language to vary.</h2></div><p>Two honest validators may phrase a summary differently. SourceWatch compares their status, severity bucket, and snapshot hash. Reasons and citations stay human-readable while the acceptance rule remains explicit.</p></section>
  <section className="about-contract"><div className="container-wide contract-bar">
    <div><span className="section-index">DEPLOYED CONTRACT</span><h2>StudioNet<br /><em>{CONTRACT_ADDRESS.slice(0, 6)}…{CONTRACT_ADDRESS.slice(-4)}</em></h2></div>
    <p>All monitor registrations and change reports are processed by this Intelligent Contract. Every baseline snapshot and semantic verdict is stored on-chain and verifiable through the GenLayer StudioNet explorer. <a href={`${EXPLORER_URL}${CONTRACT_ADDRESS}`} target="_blank" rel="noreferrer">View on explorer ↗</a></p>
  </div></section>
  <div className="about-cta"><p>Ready to put a source under watch?</p><Link to="/register" className="button button-accent">Add a source ↗</Link></div></div>;
}