import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useSourceWatch } from "../context/SourceWatchContext";

export default function Register() {
  const { wallet, contract } = useSourceWatch();
  const navigate = useNavigate();
  const [label, setLabel] = useState(""); const [description, setDescription] = useState(""); const [url, setUrl] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(null); setMessage(null); if (!wallet.address) { await wallet.connect(); return; } if (label.trim().length < 3 || description.trim().length < 20 || !url.startsWith("https://")) { setError("Use a label of at least 3 characters, a description of at least 20 characters, and a public HTTPS URL."); return; } setBusy(true); setMessage("Submitting the page for baseline consensus…"); try { const tx = await contract.registerSource(label.trim(), description.trim(), url.trim()); await contract.waitForReceipt(tx); setMessage("Baseline committed. Opening the source…"); const sources = await contract.listOwnerSources(wallet.address); const newest = sources[sources.length - 1]; if (newest) navigate(`/source/${newest.id}`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Registration failed."); setMessage(null); } finally { setBusy(false); } }
  return <div className="container-narrow page"><Link to="/sources" className="back-link">← Back to monitors</Link><div className="page-heading compact"><div><span className="section-index">REGISTER / NEW SOURCE</span><h1>Put a document<br /><em>under watch.</em></h1><p>SourceWatch will fetch the page through GenLayer validators and commit the exact baseline they agree on.</p></div></div><div className="register-layout"><form className="register-form" onSubmit={submit}><label>Source label<input value={label} onChange={(event) => setLabel(event.target.value)} placeholder="Acme API pricing" maxLength={80} /></label><label>What should watchers understand?<textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Monitor pricing, usage limits, and availability changes that affect our integration." rows={4} maxLength={1000} /><small>{description.length} / 1000</small></label><label>Public HTTPS URL<input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://docs.example.com/pricing" type="url" /></label>{error && <div className="error-box">{error}</div>}{message && <div className="status-box"><span className={busy ? "loader small-loader" : "check-mark"}>{busy ? "" : "✓"}</span>{message}</div>}<button className="button button-accent full-button" disabled={busy}>{busy ? "Waiting for consensus…" : wallet.address ? "Commit baseline" : "Connect wallet to continue"} <span>↗</span></button></form><aside className="register-note"><span className="section-index">WHAT GETS COMMITTED</span><div className="note-step"><b>01</b><span><strong>Exact text snapshot</strong><small>The text validators actually read, capped and stored on-chain.</small></span></div><div className="note-step"><b>02</b><span><strong>Keccak-256 hash</strong><small>A compact identity for the baseline version.</small></span></div><div className="note-step"><b>03</b><span><strong>Semantic history</strong><small>Future checks compare meaning, not a brittle HTML diff.</small></span></div></aside></div></div>;
}
